version: '3.8'

services:
  redis:
    image: redis/redis-stack:latest
    container_name: fr-monitor-redis
    ports:
      - "6379:6379"
      - "8001:8001"  # RedisInsight web UI
    volumes:
      - redis_data:/data
    environment:
      - REDIS_ARGS=--save 60 1000
    restart: unless-stopped

volumes:
  redis_data:
    driver: local
